# DEV environment, one image contains all
version: '2'
services:
    docker-ssh-lamp:
        build: .
        hostname: docker-ssh-lamp
        image: docker-ssh-lamp
        volumes:
          - ./app:/app
          - ./mysql:/var/lib/mysql
          - ./var_log:/var/log
          - ./www:/var/www
        ports:
          - "80:80" # Both 2080 and 8000 port are using apache
          - "1022:22"
          - "3306:3306"
        networks:
          - bridge_eth1
        container_name: "docker-ssh-lamp"
        entrypoint: /app/docker_start.sh
networks:
    bridge_eth1:
        external: true
